import Head from "next/head";
// components
import Navbar from "../components/molecules/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bassam - Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </div>
  );
}
