// components
import Head from "next/head";
import Navbar from "../components/molecules/Navbar";
import Main from "../components/molecules/Main";
import About from "../components/molecules/About";
import Skills from "../components/molecules/Skills";
import Projects from "../components/molecules/projects/Projects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bassam - Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Main />

      <About />

      <Skills />

      <Projects />
    </div>
  );
}
